# Generated by Django 4.2.16 on 2024-10-24 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renobridge.contractor')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renobridge.homeowner')),
            ],
        ),
    ]
