# Generated by Django 4.2.16 on 2024-10-22 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('property_type', models.CharField(max_length=100)),
                ('property_size', models.CharField(max_length=100)),
                ('preferred_style', models.CharField(max_length=100)),
                ('services_required', models.TextField()),
                ('budget', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('company_address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=254)),
                ('years_of_experience', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('preferred_location', models.CharField(max_length=100)),
                ('services_provided', models.TextField()),
                ('expertise_styles', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
