# Generated by Django 4.2.16 on 2024-10-28 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processes_required', models.JSONField(blank=True, null=True)),
                ('processes_completed', models.JSONField(blank=True, null=True)),
                ('budget_allocated', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expenses_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_duration', models.PositiveIntegerField(blank=True, help_text='Expected total duration in days', null=True)),
                ('duration_spent', models.PositiveIntegerField(default=0, help_text='Actual duration spent in days')),
                ('progress_percentage', models.FloatField(default=0)),
                ('contractor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='renobridge.contractor')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='renobridge.homeowner')),
            ],
        ),
    ]
