# Generated by Django 4.2.16 on 2024-11-16 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0002_remove_projectphoto_project_progressphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressphoto',
            name='contractor',
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='renobridge.project'),
        ),
    ]
