# Generated by Django 4.2.16 on 2024-10-24 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0002_collaborationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectphoto',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renobridge.contractor'),
        ),
    ]
