# Generated by Django 4.2.16 on 2024-10-28 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0003_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='custom_processes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
