# Generated by Django 4.2.16 on 2024-10-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0003_projectphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
