# Generated by Django 4.2.16 on 2024-10-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0004_contractor_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='floorplan_img',
            field=models.ImageField(blank=True, null=True, upload_to='floorplans/'),
        ),
    ]
