# Generated by Django 4.2.16 on 2024-10-28 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0004_project_custom_processes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='custom_processes',
        ),
    ]
