# Generated by Django 4.2.16 on 2024-10-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0005_homeowner_floorplan_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='full_name',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
    ]
