# Generated by Django 4.2.16 on 2024-11-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0007_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeowner',
            name='full_address',
            field=models.TextField(default='Not provided', max_length=400),
            preserve_default=False,
        ),
    ]
