# Generated by Django 4.2.16 on 2024-11-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('renobridge', '0008_homeowner_full_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='renobridge.contractor')),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renobridge.homeowner')),
            ],
        ),
    ]
